version: '3.7'

services:
    classifier-microservice:
        build:
            context: classifier-microservice
        image: classifier-microservice
        restart: unless-stopped
        expose:
            - "5000"
        deploy:
            replicas: 3


    nginx-balancer:
        image: nginx
        container_name: nginx-balancer
        restart: unless-stopped
        volumes:
            - ./nginx-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - classifier-microservice
        ports:
            - "5000:4000"